### DO NOT PUSH THESE TO PRODUCTION.
### HI, PUT YOUR API KEYS HERE. CURRENTLY ONLY OPENAI APIS ARE SUPPORTED.
### DO NOT CHANGE THE NAME OF THIS FILE, OR YOU ARE RISKING LEAKING YOUR API KEYS!
OPENAI_API_KEY=""
# NONE OF THESE CAN BE LEFT BLANK.
